

SELECT PROVINCE_SEQ, PROVINCE_ID, PROVINCE_ABBR, 
    PROVINCE_NAME_TH, PROVINCE_NAME_EN, 
    REGION_SEQ, COUNTRY_SEQ, 
    PROVINCE_DOL_ID, PROVINCE_EVD_ID, PROVINCE_DPIS_ID, 
    RECORD_STATUS, 
    CREATE_USER, CREATE_DTM, LAST_UPD_USER, LAST_UPD_DTM 
FROM MAS_.TB_MAS_PROVINCE 
WHERE 1 = 1 
    -- AND PROVINCE_SEQ = :arg 
ORDER BY PROVINCE_NAME_TH ASC NULLS LAST, PROVINCE_ID ASC NULLS LAST 


