

UPDATE MAS_.TB_MAS_PROVINCE SET 
    -- PROVINCE_SEQ = :PROVINCE_SEQ, 
    PROVINCE_ID = :PROVINCE_ID, PROVINCE_ABBR = :PROVINCE_ABBR, 
    PROVINCE_NAME_TH = :PROVINCE_NAME_TH, 
    PROVINCE_NAME_EN = :PROVINCE_NAME_EN, 
    PROVINCE_TYPE_SEQ = :PROVINCE_TYPE_SEQ, 
    PROVINCE_NOTE = :PROVINCE_NOTE, 
    RECORD_STATUS = :RECORD_STATUS, 
    -- CREATE_USER = :CREATE_USER, CREATE_DTM = :CREATE_DTM, 
    LAST_UPD_USER = :LAST_UPD_USER, LAST_UPD_DTM = SYSDATE -- :LAST_UPD_DTM 
WHERE 1 = 1 
    AND PROVINCE_SEQ = :arg 


