

INSERT /*+ APPEND */ 
INTO MAS_.TB_MAS_SCALE INS_TBL ( 
    SCALE_SEQ, SCALE_SYS_, 
    SCALE_ID, SCALE_ABBR, 
    SCALE_NAME_TH, SCALE_NAME_EN, 
    SCALE_PAGE_QTY, SCALE_NOTE, 
    RECORD_STATUS, CREATE_USER, 
    CREATE_DTM
    --LAST_UPD_USER, LAST_UPD_DTM 
) VALUES ( 
    MAS_.SQ_MAS_SCALE_SCALE_SEQ.NEXTVAL, :SCALE_SYS_, 
    :SCALE_ID, :SCALE_ABBR, 
    :SCALE_NAME_TH, :SCALE_NAME_EN, 
    :SCALE_PAGE_QTY, :SCALE_NOTE, 
    :RECORD_STATUS, :CREATE_USER, 
    SYSDATE --:CREATE_DTM, 
    --:LAST_UPD_USER, :LAST_UPD_DTM 
) 


