

SELECT SCALE_SEQ, SCALE_SYS_, 
    SCALE_ID, SCALE_ABBR, 
    SCALE_NAME_TH, SCALE_NAME_EN, 
    SCALE_PAGE_QTY, 
    SCALE_NOTE, 
    RECORD_STATUS, 
    CREATE_USER, CREATE_DTM, LAST_UPD_USER, LAST_UPD_DTM 
FROM MAS_.TB_MAS_SCALE 
WHERE 1 = 1 
    -- AND SCALE_SEQ = :arg 
ORDER BY SCALE_SYS_ ASC NULLS LAST, SCALE_NAME_TH ASC NULLS LAST, SCALE_ID ASC NULLS LAST 


