

UPDATE MAS_.TB_MAS_SCALE SET 
    -- SCALE_SEQ = :SCALE_SEQ, 
    SCALE_SYS_ = :SCALE_SYS_, 
    SCALE_ID = :SCALE_ID, SCALE_ABBR = :SCALE_ABBR, 
    SCALE_NAME_TH = :SCALE_NAME_TH, 
    SCALE_NAME_EN = :SCALE_NAME_EN, 
    SCALE_PAGE_QTY = :SCALE_PAGE_QTY, 
    SCALE_NOTE = :SCALE_NOTE, 
    RECORD_STATUS = :RECORD_STATUS, 
    -- CREATE_USER = :CREATE_USER, CREATE_DTM = :CREATE_DTM, 
    LAST_UPD_USER = :LAST_UPD_USER, LAST_UPD_DTM = SYSDATE -- :LAST_UPD_DTM 
WHERE 1 = 1 
    AND SCALE_SEQ = :arg 


