SELECT TCASDAS.CADASTRAL_SEQ  ,
TCASDAS.LANDOFFICE_SEQ , 
TCASDAS.SHEETCODE , 
TCASDAS.BOX_NO , 
TCASDAS.CADASTRAL_NO ,
TCASDAS.NUMOFSURVEY_QTY 
FROM SVA_.TB_SVA_CADASTRAL tCasdas 
INNER JOIN SVA_.TB_SVA_CADASTRAL_LAND tLand 
ON TCASDAS.CADASTRAL_SEQ  = TLAND.CADASTRAL_SEQ 
WHERE 1=1
        AND (:UTMMAP1 IS NULL OR TLAND.CADASTRAL_LAND_UTMMAP1 = :UTMMAP1)
        AND (:UTMMAP2 IS NULL OR TLAND.CADASTRAL_LAND_UTMMAP2 = :UTMMAP2)
        AND (:UTMMAP3 IS NULL OR TLAND.CADASTRAL_LAND_UTMMAP3 = :UTMMAP3)
        AND (:UTMMAP4 IS NULL OR TLAND.CADASTRAL_LAND_UTMMAP4 = :UTMMAP4)
        AND (:UTMSCALE IS NULL OR TLAND.SCALE_MAP = :UTMSCALE)
        AND (:LAND_NO IS NULL OR TLAND.CADASTRAL_LAND_NO = :LAND_NO)
GROUP BY tCasdas.CADASTRAL_SEQ , tCasdas.LANDOFFICE_SEQ , tCasdas.SHEETCODE , tCasdas.BOX_NO , tCasdas.CADASTRAL_NO , tCasdas.NUMOFSURVEY_QTY