SELECT ROWNUM , TITLE_SEQ , TITLE_NAME_TH , SURVEYOR_NAME , SURVEYOR_FNAME , SURVEYOR_LNAME FROM (
 SELECT TNAME.TITLE_SEQ , TTITLE.TITLE_NAME_TH , SURVEYOR_NAME , SURVEYOR_FNAME , SURVEYOR_LNAME FROM (
 SELECT TITLE_SEQ ,  SURVEYOR_FNAME || ' ' ||  SURVEYOR_LNAME  AS SURVEYOR_NAME  ,
 SURVEYOR_FNAME , SURVEYOR_LNAME
 FROM SVA_.TB_SVA_CADASTRAL 
 WHERE  (:SURVEYOR_FNAME IS NULL OR SURVEYOR_FNAME = :SURVEYOR_FNAME)
 AND (:SURVEYOR_LNAME IS NULL OR SURVEYOR_LNAME = :SURVEYOR_LNAME)
 GROUP BY TITLE_SEQ , SURVEYOR_FNAME , SURVEYOR_LNAME 
 ) tName 
 LEFT JOIN MAS_.TB_MAS_TITLE tTitle 
ON TNAME.TITLE_SEQ = TTITLE.TITLE_SEQ 
) t
ORDER BY SURVEYOR_FNAME , SURVEYOR_LNAME