SELECT * FROM (
SELECT 
 t.CADASTRAL_SEQ,
 t.CADASTRAL_NO,
 t.SHEETCODE,
 t.BOX_NO,
 t.NUMOFSURVEY_QTY,
 t.LANDOFFICE_SEQ,
 t.PROCESS_SEQ_,
 t.STATUS_SEQ_,
 t.CADASTRAL_NOTE,
 t.RECORD_STATUS,
 t.CREATE_USER,
 t.CREATE_DTM,
 t.LAST_UPD_USER,
 t.LAST_UPD_DTM
 FROM SVA_.TB_SVA_CADASTRAL t
 INNER JOIN EVD_.TB_EVD_CADASTRAL_IMAGE TINDEX 
 ON TINDEX.LANDOFFICE_SEQ = T.LANDOFFICE_SEQ 
 AND TINDEX.SHEETCODE = T.SHEETCODE 
 AND TINDEX.BOX_NO = T.BOX_NO 
 AND TINDEX.CADASTRAL_NO = T.CADASTRAL_NO 
 WHERE t.RECORD_STATUS = 'N'
 AND TINDEX.CADASTRAL_IMAGE = 1
 AND (:LANDOFFICE_SEQ IS NULL OR t.LANDOFFICE_SEQ = :LANDOFFICE_SEQ)
 AND (:SHEETCODE IS NULL OR t.SHEETCODE = :SHEETCODE)
 AND (:BOX_NO IS NULL OR t.BOX_NO = :BOX_NO)
 AND (:CADASTRAL_NO IS NULL OR t.CADASTRAL_NO >= :CADASTRAL_NO)
 AND (:CADASTRAL_NO_ IS NULL OR t.CADASTRAL_NO <= :CADASTRAL_NO_)
 AND (:CADASTRAL_SEQ IS NULL OR t.CADASTRAL_SEQ = :CADASTRAL_SEQ)
 AND (:NUMOFSURVEY_QTY IS NULL OR t.NUMOFSURVEY_QTY = :NUMOFSURVEY_QTY)
 ORDER BY t.LANDOFFICE_SEQ, t.SHEETCODE, t.BOX_NO, t.CADASTRAL_NO, t.NUMOFSURVEY_QTY
 ) t
-- WHERE (:STATUS_108 IS NULL OR t.STATUS_108 = :STATUS_108)
 