SELECT 
	T.LANDOFFICE_SEQ , 
	T.AMPHUR_SEQ ,   
	masAMPHUR.AMPHUR_NAME_TH  , 
	T.TAMBOL_SEQ , 
	masT.TAMBOL_NAME_TH 
FROM (
SELECT LANDOFFICE_SEQ , AMPHUR_SEQ  , TAMBOL_SEQ  FROM REG_.TB_REG_PARCEL
 WHERE LANDOFFICE_SEQ  = :LANDOFFICE_SEQ
) T 
LEFT JOIN MAS_.TB_MAS_AMPHUR masAMPHUR
ON T.AMPHUR_SEQ = masAMPHUR.AMPHUR_SEQ
LEFT JOIN MAS_.TB_MAS_TAMBOL masT 
ON T.TAMBOL_SEQ = masT.TAMBOL_SEQ 

GROUP BY T.LANDOFFICE_SEQ , 
	T.AMPHUR_SEQ ,   
	masAMPHUR.AMPHUR_NAME_TH  , 
	T.TAMBOL_SEQ , 
	masT.TAMBOL_NAME_TH 