SELECT T1.*, T2.PROVINCE_NAME_TH FROM MAS_.TB_MAS_LANDOFFICE T1
LEFT JOIN MAS_.TB_MAS_PROVINCE T2
ON T1.PROVINCE_SEQ = T2.PROVINCE_SEQ
WHERE T1.RECORD_STATUS = 'N'
AND T1.LANDOFFICE_SEQ = :LANDOFFICE_SEQ 