SELECT LANDOFFICE_SEQ, LANDOFFICE_SYS_, LANDOFFICE_NO, LANDOFFICE_ID, LANDOFFICE_ABBR, LANDOFFICE_NAME_TH, LANDOFFICE_NAME_EN, PROVINCE_SEQ,
PC_SERVER, CADASTRAL_SEQ, CADASTRAL_IMAGE_SEQ, IP_ADDRESS, LANDOFFICE_NOTE, RECORD_STATUS, CREATE_USER, CREATE_DTM, LAST_UPD_USER, LAST_UPD_DTM
FROM SVA_.TB_MAS_LANDOFFICE 
WHERE 1 = 1 
    AND IP_ADDRESS IS NOT NULL 
    -- AND LANDOFFICE_SEQ = :arg 
ORDER BY LANDOFFICE_NAME_TH ASC NULLS LAST, LANDOFFICE_ID ASC NULLS LAST 