

MERGE INTO SVA_.TB_SVA_CADASTRAL_LAND Target_ 
USING ( 
    SELECT :arg CADASTRAL_LAND_SEQ, 
        :CADASTRAL_LAND_ORDER CADASTRAL_LAND_ORDER, TO_DATE( :CADASTRAL_LAND_REGDTM, 'YYYY-MM-DD' ) CADASTRAL_LAND_REGDTM, 
        :CADASTRAL_LAND_REGDESC CADASTRAL_LAND_REGDESC, 
        :CADASTRAL_LAND_REGNAME CADASTRAL_LAND_REGNAME, 
        :CADASTRAL_LAND_PRINTED CADASTRAL_LAND_PRINTED, 
        :CADASTRAL_LAND_STS CADASTRAL_LAND_STS, 
        :CADASTRAL_LAND_CANCEL_DTM CADASTRAL_LAND_CANCEL_DTM, 
        :CADASTRAL_LAND_CANCEL_REM CADASTRAL_LAND_CANCEL_REM, 
        :PARCEL_SEQ PARCEL_SEQ, 
        :REGISTER_SEQ REGISTER_SEQ, 
        :REQUEST_SEQ REQUEST_SEQ, 
        :PROCESS_SEQ PROCESS_SEQ, 
        :HOLD_LAND_SEQ HOLD_LAND_SEQ, 
        :CADASTRAL_LAND_STS_ CADASTRAL_LAND_STS_, 
        :CADASTRAL_LAND_LOG_SEQ CADASTRAL_LAND_LOG_SEQ, 
        :PROCESS_SEQ_ PROCESS_SEQ_, 
        :STATUS_SEQ_ STATUS_SEQ_, 
        :CADASTRAL_LAND_NOTE CADASTRAL_LAND_NOTE, 
        :RECORD_STATUS RECORD_STATUS, 
        :CREATE_USER CREATE_USER, SYSDATE CREATE_DTM, 
        :CREATE_USER LAST_UPD_USER, SYSDATE LAST_UPD_DTM 
    FROM DUAL 
    WHERE 1 = 1 
) Source_ 
    ON ( Source_.CADASTRAL_LAND_SEQ = Target_.CADASTRAL_LAND_SEQ ) 

WHEN NOT MATCHED THEN 
    INSERT ( 
        CADASTRAL_LAND_SEQ, 
        CADASTRAL_LAND_ORDER, CADASTRAL_LAND_REGDTM, 
        CADASTRAL_LAND_REGDESC, CADASTRAL_LAND_REGNAME, 
        CADASTRAL_LAND_PRINTED, CADASTRAL_LAND_STS, 
        CADASTRAL_LAND_CANCEL_DTM, CADASTRAL_LAND_CANCEL_REM, 
        PARCEL_SEQ, REGISTER_SEQ, 
        REQUEST_SEQ, PROCESS_SEQ, HOLD_LAND_SEQ, 
        CADASTRAL_LAND_STS_, 
        CADASTRAL_LAND_LOG_SEQ, 
        PROCESS_SEQ_, STATUS_SEQ_, 
        CADASTRAL_LAND_NOTE, 
        RECORD_STATUS, 
        CREATE_USER, CREATE_DTM--, LAST_UPD_USER, LAST_UPD_DTM 
    ) VALUES ( 
        SVA_.SQ_SVA_CADASTRAL_LAND_SEQ.NEXTVAL, 
        Source_.CADASTRAL_LAND_ORDER, Source_.CADASTRAL_LAND_REGDTM, 
        Source_.CADASTRAL_LAND_REGDESC, Source_.CADASTRAL_LAND_REGNAME, 
        Source_.CADASTRAL_LAND_PRINTED, Source_.CADASTRAL_LAND_STS, 
        Source_.CADASTRAL_LAND_CANCEL_DTM, Source_.CADASTRAL_LAND_CANCEL_REM, 
        Source_.PARCEL_SEQ, Source_.REGISTER_SEQ, 
        Source_.REQUEST_SEQ, Source_.PROCESS_SEQ, Source_.HOLD_LAND_SEQ, 
        Source_.CADASTRAL_LAND_STS_, 
        Source_.CADASTRAL_LAND_LOG_SEQ, 
        Source_.PROCESS_SEQ_, Source_.STATUS_SEQ_, 
        Source_.CADASTRAL_LAND_NOTE, 
        Source_.RECORD_STATUS, 
        Source_.CREATE_USER, Source_.CREATE_DTM--, Source_.LAST_UPD_USER, Source_.LAST_UPD_DTM 
    ) 

WHEN MATCHED THEN 
    UPDATE SET 
        -- Target_.CADASTRAL_LAND_SEQ = Source_.CADASTRAL_LAND_SEQ, 
        Target_.CADASTRAL_LAND_ORDER = Source_.CADASTRAL_LAND_ORDER, 
        Target_.CADASTRAL_LAND_REGDTM = TO_DATE( :CADASTRAL_LAND_REGDTM, 'YYYY-MM-DD' ), 
        Target_.CADASTRAL_LAND_REGDESC = Source_.CADASTRAL_LAND_REGDESC, 
        Target_.CADASTRAL_LAND_REGNAME = Source_.CADASTRAL_LAND_REGNAME, 
        Target_.CADASTRAL_LAND_PRINTED = Source_.CADASTRAL_LAND_PRINTED, 
        Target_.CADASTRAL_LAND_STS = Source_.CADASTRAL_LAND_STS, 
        Target_.CADASTRAL_LAND_CANCEL_DTM = Source_.CADASTRAL_LAND_CANCEL_DTM, 
        Target_.CADASTRAL_LAND_CANCEL_REM = Source_.CADASTRAL_LAND_CANCEL_REM, 
        Target_.PARCEL_SEQ = Source_.PARCEL_SEQ, 
        Target_.REGISTER_SEQ = Source_.REGISTER_SEQ, 
        Target_.REQUEST_SEQ = Source_.REQUEST_SEQ, 
        Target_.PROCESS_SEQ = Source_.PROCESS_SEQ, 
        Target_.HOLD_LAND_SEQ = Source_.HOLD_LAND_SEQ, 
        Target_.CADASTRAL_LAND_STS_ = Source_.CADASTRAL_LAND_STS_, 
        Target_.CADASTRAL_LAND_LOG_SEQ = Source_.CADASTRAL_LAND_LOG_SEQ, 
        Target_.PROCESS_SEQ_ = Source_.PROCESS_SEQ_, 
        Target_.STATUS_SEQ_ = Source_.STATUS_SEQ_, 
        Target_.CADASTRAL_LAND_NOTE = Source_.CADASTRAL_LAND_NOTE, 
        Target_.RECORD_STATUS = Source_.RECORD_STATUS, 
        -- Target_.CREATE_USER = Source_.CREATE_USER, Target_.CREATE_DTM = Source_.CREATE_DTM, 
        Target_.LAST_UPD_USER = Source_.LAST_UPD_USER, Target_.LAST_UPD_DTM = Source_.LAST_UPD_DTM 


