SELECT C.CADASTRAL_LAND_SEQ, 
    C.CADASTRAL_SEQ, C.CADASTRAL_SEQ_, 
    C.LAND_ORDER, 
    C.ZONE_LAND,
    C.LANDOFFICE_SEQ, 
    C.SHEETTYPE_SEQ, C.SHEETTYPE_NAME_TH, 
    C.CADASTRAL_LAND_UTMMAP, 
    C.CADASTRAL_LAND_UTMMAP1, C.CADASTRAL_LAND_UTMMAP2, 
    C.CADASTRAL_LAND_UTMMAP3, C.CADASTRAL_LAND_UTMMAP4, 
    C.CADASTRAL_LAND_UTMMAP1_, C.CADASTRAL_LAND_UTMMAP2_, 
    C.CADASTRAL_LAND_UTMMAP3_, C.CADASTRAL_LAND_UTMMAP4_, 
    C.CADASTRAL_LAND_ORIGINMAP, 
    C.CADASTRAL_LAND_ORIGINMAP1, C.CADASTRAL_LAND_ORIGINMAP2, C.CADASTRAL_LAND_ORIGINMAP3, 
    C.CADASTRAL_LAND_ORIGINMAP1_, NVL( C.CADASTRAL_LAND_ORIGINMAP2_, C.CADASTRAL_LAND_ORIGINMAP2 ) CADASTRAL_LAND_ORIGINMAP2_, 
    C.CADASTRAL_LAND_ORIGINMAP3_, 
    C.CADASTRAL_LAND_NO, C.CADASTRAL_LAND_NO_, 
    C.AIRPHOTOMAP_NAME, 
    C.AIRPHOTOMAP, 
    C.AIRPHOTOMAP1, C.AIRPHOTOMAP2, C.AIRPHOTOMAP3, 
    C.AIRPHOTOMAP1_, C.AIRPHOTOMAP2_, C.AIRPHOTOMAP3_, 
    C.SCALE_SEQ, C.SCALE_MAP, C.SCALE_MAP_, 
    C.CADASTRAL_LAND_RAI_NUM, C.CADASTRAL_LAND_NGAN_NUM, 
    C.CADASTRAL_LAND_WA_NUM, C.CADASTRAL_LAND_SUBWA_NUM, 
    C.CADASTRAL_PROVINCE_SEQ, C.CADASTRAL_AMPHUR_SEQ, C.CADASTRAL_TAMBOL_SEQ, 
    C.CADASTRAL_SURVEY_NO, NVL( C.CADASTRAL_SURVEY_NO_, C.CADASTRAL_SURVEY_NO ) CADASTRAL_SURVEY_NO_, 
    C.STATIC_FLAG, 
    C.PARCEL_SEQ, 
    C.CADASTRAL_LAND_LOG_SEQ, 
    C.PROCESS_SEQ_, STATUS_SEQ_, 
    C.CADASTRAL_LAND_NOTE, 
    C.RECORD_STATUS, 
    C.CREATE_USER, C.CREATE_DTM, C.LAST_UPD_USER ,C.LAST_UPD_DTM,
    L.LANDOFFICE_NAME_TH ,P.PROVINCE_NAME_TH, A.AMPHUR_NAME_TH ,T.TAMBOL_NAME_TH 
FROM SVA_.TB_SVA_CADASTRAL_LAND C
INNER JOIN 
    MAS_.TB_MAS_LANDOFFICE L 
ON 
    C.LANDOFFICE_SEQ = L.LANDOFFICE_SEQ
INNER JOIN 
	MAS_.TB_MAS_PROVINCE P
ON
	C.CADASTRAL_PROVINCE_SEQ  = P.PROVINCE_SEQ 
INNER JOIN 
	MAS_.TB_MAS_TAMBOL T
ON
	C.CADASTRAL_TAMBOL_SEQ = T.TAMBOL_SEQ
INNER JOIN 
	MAS_.TB_MAS_AMPHUR A
ON
	C.CADASTRAL_AMPHUR_SEQ  = A.AMPHUR_SEQ 
WHERE 1 = 1 
    -- AND CADASTRAL_LAND_SEQ = :arg 
ORDER BY ZONE_LAND ASC NULLS LAST, 
    CADASTRAL_LAND_UTMMAP1 ASC NULLS LAST, CADASTRAL_LAND_UTMMAP2 ASC NULLS LAST, CADASTRAL_LAND_UTMMAP3 ASC NULLS LAST, 
    SCALE_MAP DESC NULLS LAST, CADASTRAL_LAND_UTMMAP4 ASC NULLS LAST, 
    CADASTRAL_LAND_NO ASC NULLS LAST 

