

UPDATE SVA_.TB_SVA_CADASTRAL_LAND SET 
    -- CADASTRAL_LAND_SEQ = :CADASTRAL_LAND_SEQ, 
    CADASTRAL_SEQ = :CADASTRAL_SEQ, CADASTRAL_SEQ_ = :CADASTRAL_SEQ_, 
    LAND_ORDER = :LAND_ORDER, 
    ZONE_LAND = :ZONE_LAND, 
    SHEETTYPE_SEQ = :SHEETTYPE_SEQ, SHEETTYPE_NAME_TH = :SHEETTYPE_NAME_TH, 
    CADASTRAL_LAND_UTMMAP = :CADASTRAL_LAND_UTMMAP, 
    CADASTRAL_LAND_UTMMAP1 = :CADASTRAL_LAND_UTMMAP1, CADASTRAL_LAND_UTMMAP2 = :CADASTRAL_LAND_UTMMAP2, 
    CADASTRAL_LAND_UTMMAP3 = :CADASTRAL_LAND_UTMMAP3, CADASTRAL_LAND_UTMMAP4 = :CADASTRAL_LAND_UTMMAP4, 
    CADASTRAL_LAND_UTMMAP1_ = :CADASTRAL_LAND_UTMMAP1_, CADASTRAL_LAND_UTMMAP2_ = :CADASTRAL_LAND_UTMMAP2_, 
    CADASTRAL_LAND_UTMMAP3_ = :CADASTRAL_LAND_UTMMAP3_, CADASTRAL_LAND_UTMMAP4_ = :CADASTRAL_LAND_UTMMAP4_, 
    CADASTRAL_LAND_ORIGINMAP = :CADASTRAL_LAND_ORIGINMAP, 
    CADASTRAL_LAND_ORIGINMAP1 = :CADASTRAL_LAND_ORIGINMAP1, CADASTRAL_LAND_ORIGINMAP2 = :CADASTRAL_LAND_ORIGINMAP2, CADASTRAL_LAND_ORIGINMAP3 = :CADASTRAL_LAND_ORIGINMAP3, 
    CADASTRAL_LAND_ORIGINMAP1_ = :CADASTRAL_LAND_ORIGINMAP1_, CADASTRAL_LAND_ORIGINMAP2_ = :CADASTRAL_LAND_ORIGINMAP2_, CADASTRAL_LAND_ORIGINMAP3_ = :CADASTRAL_LAND_ORIGINMAP3_, 
    CADASTRAL_LAND_NO = :CADASTRAL_LAND_NO, CADASTRAL_LAND_NO_ = :CADASTRAL_LAND_NO_, 
    AIRPHOTOMAP_NAME = :AIRPHOTOMAP_NAME, 
    AIRPHOTOMAP = :AIRPHOTOMAP, 
    AIRPHOTOMAP1 = :AIRPHOTOMAP1, AIRPHOTOMAP2 = :AIRPHOTOMAP2, AIRPHOTOMAP3 = :AIRPHOTOMAP3, 
    AIRPHOTOMAP1_ = :AIRPHOTOMAP1_, AIRPHOTOMAP2_ = :AIRPHOTOMAP2_, AIRPHOTOMAP3_ = :AIRPHOTOMAP3_, 
    SCALE_SEQ = :SCALE_SEQ, SCALE_MAP = :SCALE_MAP, SCALE_MAP_ = :SCALE_MAP_, 
    CADASTRAL_LAND_RAI_NUM = :CADASTRAL_LAND_RAI_NUM, CADASTRAL_LAND_NGAN_NUM = :CADASTRAL_LAND_NGAN_NUM, 
    CADASTRAL_LAND_WA_NUM = :CADASTRAL_LAND_WA_NUM, CADASTRAL_LAND_SUBWA_NUM = :CADASTRAL_LAND_SUBWA_NUM, 
    CADASTRAL_PROVINCE_SEQ = :CADASTRAL_PROVINCE_SEQ, CADASTRAL_PROVINCE_NAME_TH = :CADASTRAL_PROVINCE_NAME_TH, 
    CADASTRAL_AMPHUR_SEQ = :CADASTRAL_AMPHUR_SEQ, CADASTRAL_AMPHUR_NAME_TH = :CADASTRAL_AMPHUR_NAME_TH, 
    CADASTRAL_TAMBOL_SEQ = :CADASTRAL_TAMBOL_SEQ, CADASTRAL_TAMBOL_NAME_TH = :CADASTRAL_TAMBOL_NAME_TH, 
    CADASTRAL_SURVEY_NO = :CADASTRAL_SURVEY_NO, CADASTRAL_SURVEY_NO_ = :CADASTRAL_SURVEY_NO_, 
    STATIC_FLAG = :STATIC_FLAG, 
    PARCEL_SEQ = :PARCEL_SEQ, 
    CADASTRAL_LAND_LOG_SEQ = :CADASTRAL_LAND_LOG_SEQ, 
    PROCESS_SEQ_ = :PROCESS_SEQ_, STATUS_SEQ_ = :STATUS_SEQ_, 
    CADASTRAL_LAND_NOTE = :CADASTRAL_LAND_NOTE, 
    RECORD_STATUS = :RECORD_STATUS, 
    -- CREATE_USER = :CREATE_USER, CREATE_DTM = :CREATE_DTM, 
    LAST_UPD_USER = :LAST_UPD_USER, LAST_UPD_DTM = SYSDATE -- :LAST_UPD_DTM 
WHERE 1 = 1 
    AND CADASTRAL_LAND_SEQ = :arg 


