

INSERT /*+ APPEND */ 
INTO MAS_.TB_MAS_AMPHUR INS_TBL ( 
    AMPHUR_SEQ, AMPHUR_SYS_, 
    AMPHUR_ID, AMPHUR_ABBR, 
    AMPHUR_NAME_TH, AMPHUR_NAME_EN, 
    AMPHUR_TYPE_SEQ, AMPHUR_NOTE, 
    RECORD_STATUS, CREATE_USER, 
    CREATE_DTM
    --LAST_UPD_USER, LAST_UPD_DTM 
) VALUES ( 
    MAS_.SQ_MAS_AMPHUR_AMPHUR_SEQ.NEXTVAL, :AMPHUR_SYS_, 
    :AMPHUR_ID, :AMPHUR_ABBR, 
    :AMPHUR_NAME_TH, :AMPHUR_NAME_EN, 
    :AMPHUR_TYPE_SEQ, :AMPHUR_NOTE, 
    :RECORD_STATUS, :CREATE_USER, 
    SYSDATE --:CREATE_DTM, 
    --:LAST_UPD_USER, :LAST_UPD_DTM 
) 


