

SELECT AMPHUR_SEQ, AMPHUR_ID, AMPHUR_ABBR, 
    AMPHUR_NAME_TH, AMPHUR_NAME_EN, 
    PROVINCE_SEQ, 
    AMPHUR_EVD_ID, AMPHUR_DOL_ID, AMPHUR_DPIS_ID, 
    RECORD_STATUS, 
    CREATE_USER, CREATE_DTM, LAST_UPD_USER, LAST_UPD_DTM 
FROM MAS_.TB_MAS_AMPHUR 
WHERE 1 = 1 
    AND AMPHUR_SEQ = :arg 
ORDER BY AMPHUR_NAME_TH ASC NULLS LAST, AMPHUR_ID ASC NULLS LAST 


