

UPDATE MAS_.TB_MAS_AMPHUR SET 
    -- AMPHUR_SEQ = :AMPHUR_SEQ, 
    AMPHUR_SYS_ = :AMPHUR_SYS_, 
    AMPHUR_ID = :AMPHUR_ID, AMPHUR_ABBR = :AMPHUR_ABBR, 
    AMPHUR_NAME_TH = :AMPHUR_NAME_TH, 
    AMPHUR_NAME_EN = :AMPHUR_NAME_EN, 
    AMPHUR_TYPE_SEQ = :AMPHUR_TYPE_SEQ, 
    AMPHUR_NOTE = :AMPHUR_NOTE, 
    RECORD_STATUS = :RECORD_STATUS, 
    -- CREATE_USER = :CREATE_USER, CREATE_DTM = :CREATE_DTM, 
    LAST_UPD_USER = :LAST_UPD_USER, LAST_UPD_DTM = SYSDATE -- :LAST_UPD_DTM 
WHERE 1 = 1 
    AND AMPHUR_SEQ = :arg 


