SELECT 
    SURVEYDOCTYPE_GROUP, 
    SURVEYDOCTYPE_SEQ, 
    SURVEYDOCTYPE_SYS_, 
    SURVEYDOCTYPE_ID, 
    SURVEYDOCTYPE_NAME_TH, 
    SURVEYDOCTYPE_NAME_EN, 
    SURVEYDOCTYPE_ORDER, 
    SURVEYDOCTYPE_NOTE, 
    RECORD_STATUS, 
    CREATE_USER, 
    CREATE_DTM, 
    LAST_UPD_USER, 
    LAST_UPD_DTM 
FROM MAS_.TB_MAS_SURVEYDOCTYPE 
WHERE 1 = 1 
GROUP BY 
    SURVEYDOCTYPE_GROUP, 
    SURVEYDOCTYPE_SEQ, 
    SURVEYDOCTYPE_SYS_, 
    SURVEYDOCTYPE_ID, 
    SURVEYDOCTYPE_NAME_TH, 
    SURVEYDOCTYPE_NAME_EN, 
    SURVEYDOCTYPE_ORDER, 
    SURVEYDOCTYPE_NOTE, 
    RECORD_STATUS, 
    CREATE_USER, 
    CREATE_DTM, 
    LAST_UPD_USER, 
    LAST_UPD_DTM 
ORDER BY 
    SURVEYDOCTYPE_SYS_ ASC NULLS LAST, 
    SURVEYDOCTYPE_NAME_TH ASC NULLS LAST, 
    SURVEYDOCTYPE_ID ASC NULLS LAST
