SELECT TYPEOFSURVEY_SEQ, TYPEOFSURVEY_SYS_, 
    TYPEOFSURVEY_ID, TYPEOFSURVEY_ABBR, 
    TYPEOFSURVEY_NAME_TH, TYPEOFSURVEY_SHORTNAME, 
    MAINTYPEOFSURVEY_SEQ, 
    GROUPTYPE_SEQ, REG_GROUPTYPE_SEQ, 
    PERFORMANCEREPORT_SEQ, 
    PRIVATE_FLAG, PROJECT_FLAG, USEOLDDOC_FLAG, 
    CAL_BY_PARCEL, CAL_BY_DAY, CAL_BY_DOC, CAL_BY_FILE, 
    FEETYPE_SEQ, ADD_FEETYPE_SEQ, 
    ADDITION_FLAG, 
    TYPEOFSURVEY_NOTE, 
    RECORD_STATUS, 
    CREATE_USER, CREATE_DTM, LAST_UPD_USER, LAST_UPD_DTM 
FROM MAS_.TB_MAS_TYPEOFSURVEY 
WHERE 1 = 1 
    -- AND TYPEOFSURVEY_SEQ = :arg 
ORDER BY TYPEOFSURVEY_SYS_ ASC NULLS LAST, TYPEOFSURVEY_NAME_TH ASC NULLS LAST, TYPEOFSURVEY_ID ASC NULLS LAST 


