package model

import "time"

type Cadastral01 struct {
	CADASTRAL_SEQ              *string    `json:"CADASTRAL_SEQ"`
	CADASTRAL_NO               *string    `json:"CADASTRAL_NO"`
	SHEETCODE                  *string    `json:"SHEETCODE"`
	BOX_NO                     *string    `json:"BOX_NO"`
	NUMOFSURVEY_QTY            *string    `json:"NUMOFSURVEY_QTY"`
	LANDOFFICE_SEQ             *string    `json:"LANDOFFICE_SEQ"`
	PRINTPLATE_TYPE_SEQ        *string    `json:"PRINTPLATE_TYPE_SEQ"`
	PRIVATESURVEY_FLAG         *string    `json:"PRIVATESURVEY_FLAG"`
	TYPEOFSURVEY_SEQ           *string    `json:"TYPEOFSURVEY_SEQ"`
	TYPEOFSURVEY_NAME_TH       *string    `json:"TYPEOFSURVEY_NAME_TH"`
	TYPEOFSURVEY_ADD1_SEQ      *string    `json:"TYPEOFSURVEY_ADD1_SEQ"`
	TYPEOFSURVEY_ADD2_SEQ      *string    `json:"TYPEOFSURVEY_ADD2_SEQ"`
	TYPEOFSURVEY_ADD3_SEQ      *string    `json:"TYPEOFSURVEY_ADD3_SEQ"`
	CADASTRAL_SURVEY_NO        *string    `json:"CADASTRAL_SURVEY_NO"`
	CADASTRAL_SURVEY_NO_       *string    `json:"CADASTRAL_SURVEY_NO_"`
	CADASTRAL_TAMBOL_SEQ       *string    `json:"CADASTRAL_TAMBOL_SEQ"`
	CADASTRAL_TAMBOL_NAME_TH   *string    `json:"CADASTRAL_TAMBOL_NAME_TH"`
	CADASTRAL_AMPHUR_SEQ       *string    `json:"CADASTRAL_AMPHUR_SEQ"`
	CADASTRAL_AMPHUR_NAME_TH   *string    `json:"CADASTRAL_AMPHUR_NAME_TH"`
	CADASTRAL_PROVINCE_SEQ     *string    `json:"CADASTRAL_PROVINCE_SEQ"`
	CADASTRAL_PROVINCE_NAME_TH *string    `json:"CADASTRAL_PROVINCE_NAME_TH"`
	ZONE_LAND                  *string    `json:"ZONE_LAND"`
	SHEETTYPE_SEQ              *string    `json:"SHEETTYPE_SEQ"`
	SHEETTYPE_NAME_TH          *string    `json:"SHEETTYPE_NAME_TH"`
	CADASTRAL_UTMMAP           *string    `json:"CADASTRAL_UTMMAP"`
	CADASTRAL_UTMMAP1          *string    `json:"CADASTRAL_UTMMAP1"`
	CADASTRAL_UTMMAP2          *string    `json:"CADASTRAL_UTMMAP2"`
	CADASTRAL_UTMMAP3          *string    `json:"CADASTRAL_UTMMAP3"`
	CADASTRAL_UTMMAP4          *string    `json:"CADASTRAL_UTMMAP4"`
	CADASTRAL_ORIGINMAP        *string    `json:"CADASTRAL_ORIGINMAP"`
	CADASTRAL_ORIGINMAP1       *string    `json:"CADASTRAL_ORIGINMAP1"`
	CADASTRAL_ORIGINMAP2       *string    `json:"CADASTRAL_ORIGINMAP2"`
	CADASTRAL_ORIGINMAP3       *string    `json:"CADASTRAL_ORIGINMAP3"`
	CADASTRAL_LAND_NO          *string    `json:"CADASTRAL_LAND_NO"`
	CADASTRAL_LAND_NO_         *string    `json:"CADASTRAL_LAND_NO_"`
	AIRPHOTOMAP_NAME           *string    `json:"AIRPHOTOMAP_NAME"`
	AIRPHOTOMAP                *string    `json:"AIRPHOTOMAP"`
	AIRPHOTOMAP1               *string    `json:"AIRPHOTOMAP1"`
	AIRPHOTOMAP2               *string    `json:"AIRPHOTOMAP2"`
	AIRPHOTOMAP3               *string    `json:"AIRPHOTOMAP3"`
	SCALE_MAP_SEQ              *string    `json:"SCALE_MAP_SEQ"`
	SCALE_MAP                  *string    `json:"SCALE_MAP"`
	SCALE_RAWANG_SEQ           *string    `json:"SCALE_RAWANG_SEQ"`
	SCALE_RAWANG               *string    `json:"SCALE_RAWANG"`
	OWNER_TITLE_SEQ            *string    `json:"OWNER_TITLE_SEQ"`
	OWNER_TITLE_NAME           *string    `json:"OWNER_TITLE_NAME"`
	OWNER_NAME                 *string    `json:"OWNER_NAME"`
	OWNER_FNAME                *string    `json:"OWNER_FNAME"`
	OWNER_LNAME                *string    `json:"OWNER_LNAME"`
	BENCHMARK_SEQ              *string    `json:"BENCHMARK_SEQ"`
	BENCHMARK_NAME_TH          *string    `json:"BENCHMARK_NAME_TH"`
	BENCHMARK_QTY              *string    `json:"BENCHMARK_QTY"`
	BENCHMARK2_SEQ             *string    `json:"BENCHMARK2_SEQ"`
	BENCHMARK2_NAME_TH         *string    `json:"BENCHMARK2_NAME_TH"`
	BENCHMARK2_QTY             *string    `json:"BENCHMARK2_QTY"`
	SURVEY_DTM                 *time.Time `json:"SURVEY_DTM"`
	SURVEY_DTM_                *string    `json:"SURVEY_DTM_"`
	SURVEYJOB_SEQ              *string    `json:"SURVEYJOB_SEQ"`
	TITLE_SEQ                  *string    `json:"TITLE_SEQ"`
	TITLE_NAME                 *string    `json:"TITLE_NAME"`
	SURVEYOR_NAME              *string    `json:"SURVEYOR_NAME"`
	SURVEYOR_FNAME             *string    `json:"SURVEYOR_FNAME"`
	SURVEYOR_LNAME             *string    `json:"SURVEYOR_LNAME"`
	SURVEYOR_POSITION          *string    `json:"SURVEYOR_POSITION"`
	SURVEYOR_POSITION_         *string    `json:"SURVEYOR_POSITION_"`
	SURVEYOR_LEVEL             *string    `json:"SURVEYOR_LEVEL"`
	OLD_RAI_NUM                *string    `json:"OLD_RAI_NUM"`
	OLD_NGAN_NUM               *string    `json:"OLD_NGAN_NUM"`
	OLD_WA_NUM                 *string    `json:"OLD_WA_NUM"`
	OLD_SUBWA_NUM              *string    `json:"OLD_SUBWA_NUM"`
	CADASTRAL_LAND_QTY         *string    `json:"CADASTRAL_LAND_QTY"`
	CADASTRAL_IMAGE_QTY        *string    `json:"CADASTRAL_IMAGE_QTY"`
	CADASTRAL_OWNER_QTY        *string    `json:"CADASTRAL_OWNER_QTY"`
	LOST_FLAG                  *string    `json:"LOST_FLAG"`
	CANCEL_FLAG                *string    `json:"CANCEL_FLAG"`
	CANCEL_USER                *string    `json:"CANCEL_USER"`
	CANCEL_CAUSE               *string    `json:"CANCEL_CAUSE"`
	CANCELJOB_FLAG             *string    `json:"CANCELJOB_FLAG"`
	CADASTRAL_SEQ_             *string    `json:"CADASTRAL_SEQ_"`
	CADASTRAL_LOG_SEQ          *string    `json:"CADASTRAL_LOG_SEQ"`
	PROCESS_SEQ_               *string    `json:"PROCESS_SEQ_"`
	STATUS_SEQ_                *string    `json:"STATUS_SEQ_"`
	CADASTRAL_NOTE             *string    `json:"CADASTRAL_NOTE"`
	RECORD_STATUS              *string    `json:"RECORD_STATUS"`
	CREATE_USER                *string    `json:"CREATE_USER"`
	CREATE_DTM                 *time.Time `json:"CREATE_DTM"`
	LAST_UPD_USER              *string    `json:"LAST_UPD_USER"`
	LAST_UPD_DTM               *time.Time `json:"LAST_UPD_DTM"`
	LANDOFFICE_NAME_TH         *string    `json:"LANDOFFICE_NAME_TH"`
	LANDOFFICE_NAME_EN         *string    `json:"LANDOFFICE_NAME_EN"`
}
