

INSERT /*+ APPEND */ 
INTO MAS_.TB_MAS_TAMBOL INS_TBL ( 
    TAMBOL_SEQ, TAMBOL_SYS_, 
    TAMBOL_ID, TAMBOL_ABBR, 
    TAMBOL_NAME_TH, TAMBOL_NAME_EN, 
    TAMBOL_TYPE_SEQ, TAMBOL_NOTE, 
    RECORD_STATUS, CREATE_USER, 
    CREATE_DTM
    --LAST_UPD_USER, LAST_UPD_DTM 
) VALUES ( 
    MAS_.SQ_MAS_TAMBOL_TAMBOL_SEQ.NEXTVAL, :TAMBOL_SYS_, 
    :TAMBOL_ID, :TAMBOL_ABBR, 
    :TAMBOL_NAME_TH, :TAMBOL_NAME_EN, 
    :TAMBOL_TYPE_SEQ, :TAMBOL_NOTE, 
    :RECORD_STATUS, :CREATE_USER, 
    SYSDATE --:CREATE_DTM, 
    --:LAST_UPD_USER, :LAST_UPD_DTM 
) 


