

SELECT TAMBOL_SEQ, TAMBOL_ID, TAMBOL_ABBR, 
    TAMBOL_NAME_TH, TAMBOL_NAME_EN, AMPHUR_SEQ, 
    TAMBOL_NOTE, 
    ZIP_CODE, 
    TAMBOL_EVD_ID, TAMBOL_DOL_ID, TAMBOL_DPIS_ID, 
    RECORD_STATUS, 
    CREATE_USER, CREATE_DTM, LAST_UPD_USER, LAST_UPD_DTM 
FROM MAS_.TB_MAS_TAMBOL 
WHERE 1 = 1 
    -- AND TAMBOL_SEQ = :arg 
ORDER BY TAMBOL_NAME_TH ASC NULLS LAST, TAMBOL_ID ASC NULLS LAST 


