

UPDATE MAS_.TB_MAS_TAMBOL SET 
    -- TAMBOL_SEQ = :TAMBOL_SEQ, 
    TAMBOL_SYS_ = :TAMBOL_SYS_, 
    TAMBOL_ID = :TAMBOL_ID, TAMBOL_ABBR = :TAMBOL_ABBR, 
    TAMBOL_NAME_TH = :TAMBOL_NAME_TH, 
    TAMBOL_NAME_EN = :TAMBOL_NAME_EN, 
    TAMBOL_TYPE_SEQ = :TAMBOL_TYPE_SEQ, 
    TAMBOL_NOTE = :TAMBOL_NOTE, 
    RECORD_STATUS = :RECORD_STATUS, 
    -- CREATE_USER = :CREATE_USER, CREATE_DTM = :CREATE_DTM, 
    LAST_UPD_USER = :LAST_UPD_USER, LAST_UPD_DTM = SYSDATE -- :LAST_UPD_DTM 
WHERE 1 = 1 
    AND TAMBOL_SEQ = :arg 


