-- SELECT 
--  tINDEX.CADASTRAL_NO,
--  TINDEX.NUMOFSURVEY_QTY ,
--  tINDEX.CADASTRAL_SEQ 
-- FROM SVA_.TB_SVA_CADASTRAL tIndex 
-- LEFT JOIN 
-- (
-- 	SELECT tCadas.LANDOFFICE_SEQ , tCadas.SHEETCODE , tCadas.BOX_NO , tCadas.CADASTRAL_NO FROM SVA_.TB_SVA_CADASTRAL tCadas 
-- 	INNER JOIN SVA_.TB_SVA_CADASTRAL_LOG tLog 
-- 	ON  tCadas.CADASTRAL_SEQ = tLog.CADASTRAL_SEQ
-- 	GROUP BY tCadas.LANDOFFICE_SEQ , tCadas.SHEETCODE , tCadas.BOX_NO , tCadas.CADASTRAL_NO
-- ) tLog 
-- ON TINDEX.LANDOFFICE_SEQ  = tLOG.LANDOFFICE_SEQ
-- AND tIndex.SHEETCODE  = tLog.SHEETCODE 
-- AND tIndex.BOX_NO = tLog.BOX_NO 
-- AND tIndex.CADASTRAL_NO  = tLog.CADASTRAL_NO
--  WHERE 
--  tIndex.LANDOFFICE_SEQ = :LANDOFFICE_SEQ  
--  AND tIndex.SHEETCODE  = :SHEETCODE 
--  AND tIndex.BOX_NO = :BOX_NO
-- ORDER BY NVL(tLog.CADASTRAL_NO,0) ASC  , tINdex.CADASTRAL_NO , TINDEX.NUMOFSURVEY_QTY
SELECT 
 tINDEX.CADASTRAL_NO,
 TINDEX.NUMOFSURVEY_QTY ,
 tINDEX.CADASTRAL_SEQ 
FROM SVA_.TB_SVA_CADASTRAL tIndex 
 WHERE 
 tIndex.LANDOFFICE_SEQ = :LANDOFFICE_SEQ  
 AND tIndex.SHEETCODE  = :SHEETCODE 
 AND tIndex.BOX_NO = :BOX_NO
ORDER BY NVL(tIndex.CADASTRAL_NO,0) ASC  , tINdex.CADASTRAL_NO , TINDEX.NUMOFSURVEY_QTY