SELECT *
FROM (
    SELECT 
        CADASTRAL_SEQ,
        SHEETCODE,
        BOX_NO,
        CADASTRAL_NO,
        NUMOFSURVEY_QTY,
        ROW_NUMBER() OVER (ORDER BY SHEETCODE, BOX_NO, CADASTRAL_NO, NUMOFSURVEY_QTY) AS ROWNUMBER
    FROM SVA_.TB_SVA_CADASTRAL
    WHERE RECORD_STATUS = 'N'
    AND LANDOFFICE_SEQ = :LANDOFFICE_SEQ
    AND (STATUS_SEQ_ != 101 OR STATUS_SEQ_ IS NULL)
    AND (
        TYPEOFSURVEY_SEQ IS NULL OR
        CADASTRAL_PROVINCE_SEQ IS NULL OR
        CADASTRAL_AMPHUR_SEQ IS NULL OR
        CADASTRAL_TAMBOL_SEQ IS NULL OR
        SURVEY_DTM IS NULL OR
        CADASTRAL_LAND_NO IS NULL OR
        CADASTRAL_SURVEY_NO IS NULL
    )
    AND (
        (:START_SHEETCODE IS NULL OR 
         (:END_SHEETCODE IS NULL AND SHEETCODE = :START_SHEETCODE) OR 
         (:END_SHEETCODE IS NOT NULL AND SHEETCODE BETWEEN :START_SHEETCODE AND :END_SHEETCODE))
    )
    AND (
        (:START_BOX IS NULL OR 
         (:END_BOX IS NULL AND BOX_NO = :START_BOX) OR 
         (:END_BOX IS NOT NULL AND BOX_NO BETWEEN :START_BOX AND :END_BOX))
    )
)
WHERE ROWNUMBER BETWEEN (:PAGE - 1) * :PAGE_ROW + 1 AND :PAGE * :PAGE_ROW
ORDER BY SHEETCODE, BOX_NO, CADASTRAL_NO, NUMOFSURVEY_QTY
