SELECT 
    SHEETCODE,
    COUNT(DISTINCT BOX_NO) AS UNIQUE_BOX_COUNT,
    COUNT(CADASTRAL_NO) AS CADASTRAL_COUNT
FROM SVA_.TB_SVA_CADASTRAL
WHERE  RECORD_STATUS  = 'N'
 AND LANDOFFICE_SEQ  = :LANDOFFICE_SEQ 
GROUP BY SHEETCODE
ORDER BY SHEETCODE