MERGE INTO SVA_.TB_SVA_CADASTRAL_LAND target
USING 
(
SELECT :OGR_FID AS OGR_FID, T1.UTMMAP1, T1.UTMMAP2, T1.UTMMAP3, T1.UTMSCALE, T2.SCALE_SEQ, T2.SCALE_NAME_TH, T1.UTMMAP4, T1.LAND_NO, T1.SURVEY_NO, T1.CADASTRAL_SEQ, T1.PARCEL_SEQ
, :CREATE_USER AS CREATE_USER 
, T1.LANDOFFICE_SEQ, T1.LANDOFFICE_ID, T1.LANDOFFICE_NAME_TH
, T1.PROVINCE_SEQ, T1.PROVINCE_ID, T1.PROVINCE_NAME_TH
, T1.AMPHUR_SEQ, T1.AMPHUR_ID, T1.AMPHUR_NAME_TH
, T1.TAMBOL_SEQ, T1.TAMBOL_ID, T1.TAMBOL_NAME_TH
FROM (
    SELECT UTMMAP1, UTMMAP2, UTMMAP3, UTMSCALE, UTMMAP4, LAND_NO, SURVEY_NO,
    :CADASTRAL_SEQ AS CADASTRAL_SEQ, :PARCEL_SEQ AS PARCEL_SEQ
    , LANDOFFICE_SEQ, LANDOFFICE_ID, LANDOFFICE_NAME_TH
    , PROVINCE_SEQ, PROVINCE_ID, PROVINCE_NAME_TH
    , AMPHUR_SEQ, AMPHUR_ID, AMPHUR_NAME_TH
    , TAMBOL_SEQ, TAMBOL_ID, TAMBOL_NAME_TH
    FROM MAP_.MAP_LAND_GIS_48
    WHERE OGR_FID = :OGR_FID
) T1
LEFT JOIN
(
    SELECT SCALE_SEQ, SCALE_SYS_, SCALE_ID, SCALE_ABBR, SCALE_NAME_TH, SCALE_NAME_EN, SCALE_PAGE_QTY, SCALE_NOTE, RECORD_STATUS, CREATE_USER, CREATE_DTM, LAST_UPD_USER, LAST_UPD_DTM
    FROM MAS_.TB_MAS_SCALE
    WHERE RECORD_STATUS = 'N'
) T2
ON T1.UTMSCALE = T2.SCALE_NAME_TH
) 
source
ON (
source.UTMMAP1 = target.CADASTRAL_LAND_UTMMAP1
AND source.UTMMAP2 = target.CADASTRAL_LAND_UTMMAP2
AND source.UTMMAP3 = target.CADASTRAL_LAND_UTMMAP3
AND source.UTMMAP4 = target.CADASTRAL_LAND_UTMMAP4
AND source.SCALE_SEQ = target.SCALE_SEQ
AND source.LAND_NO = target.CADASTRAL_LAND_NO
AND target.CADASTRAL_SEQ = :CADASTRAL_SEQ
AND target.RECORD_STATUS = 'N'
)
WHEN NOT MATCHED THEN
    INSERT (
        CADASTRAL_LAND_SEQ,
        CADASTRAL_SEQ, 
        PARCEL_SEQ, 
        ZONE_LAND, 
        CADASTRAL_LAND_UTMMAP1, 
        CADASTRAL_LAND_UTMMAP2, 
        CADASTRAL_LAND_UTMMAP3, 
        CADASTRAL_LAND_UTMMAP4,
        CADASTRAL_LAND_NO,
        CADASTRAL_SURVEY_NO,
        SCALE_SEQ,
        SCALE_MAP,
        LANDOFFICE_SEQ,
        CADASTRAL_TAMBOL_SEQ,
        CADASTRAL_TAMBOL_NAME_TH,
        CADASTRAL_AMPHUR_SEQ,
        CADASTRAL_AMPHUR_NAME_TH,
        CADASTRAL_PROVINCE_SEQ,
        CADASTRAL_PROVINCE_NAME_TH,
        CREATE_USER,
        CREATE_DTM,
        RECORD_STATUS
    )
    VALUES (
        SVA_.SQ_SVA_CADASTRAL_LAND_SEQ.NEXTVAL, 
        source.CADASTRAL_SEQ, 
        -- source.PARCEL_SEQ, 
        source.OGR_FID, 
        :ZONE_LAND, 
        source.UTMMAP1, 
        source.UTMMAP2, 
        source.UTMMAP3, 
        source.UTMMAP4, 
        source.LAND_NO, 
        source.SURVEY_NO, 
        source.SCALE_SEQ, 
        source.UTMSCALE, 
        source.LANDOFFICE_SEQ,
        source.TAMBOL_SEQ,
        source.TAMBOL_NAME_TH,
        source.AMPHUR_SEQ,
        source.AMPHUR_NAME_TH,
        source.PROVINCE_SEQ,
        source.PROVINCE_NAME_TH,
        source.CREATE_USER,
        SYSDATE,
        'N'
        )